kkbox2468/TypingPractice-2.0.0

app/assets/stylesheets/user_article.scss
app/controllers/user_article_controller.rb
app/helpers/user_article_helper.rb
test/controllers/user_article_controller_test.rb

add UserArticle_controller

---

app/controllers/stats_controller.rb
app/controllers/user_article_controller.rb
app/javascript/scripts/playground.js
app/javascript/styles/index.js
app/javascript/styles/playground.css
app/javascript/styles/typing.css
app/javascript/styles/welcome.css
app/views/stats/index.html.erb
app/views/typing/index.html.erb
app/views/typing/show.html.erb

1.成績分析已經可以使用、但params還沒抓完全、資料不齊全是正常的
2.進入typing 頁面的關卡選擇、 樣式已經統一完成

開啟成績分析頁面、更改選擇關卡樣式

---

app/controllers/concerns/accessible.rb
app/controllers/users/sessions_controller.rb

fix logout

---

app/assets/stylesheets/messages.scss
app/assets/stylesheets/racing.scss
app/channels/room_channel.rb
app/controllers/messages_controller.rb
app/controllers/racing_controller.rb
app/controllers/rooms_controller.rb
app/helpers/messages_helper.rb
app/helpers/racing_helper.rb
app/javascript/channels/room_channel.js
app/javascript/packs/application.js
app/javascript/packs/channels.js
app/javascript/scripts/playground.js
app/javascript/styles/playground.css
app/views/playground/index.html.erb
app/views/racing/index.html.erb
app/views/rooms/_quote.html.erb
app/views/rooms/edit.html.erb
app/views/rooms/show.html.erb
config/routes.rb
test/channels/room_channel_test.rb
test/controllers/messages_controller_test.rb
test/controllers/racing_controller_test.rb

action cable功能實裝

---

app/models/battle_record.rb
app/models/user.rb
db/migrate/20200519035634_create_battle_records.rb
db/schema.rb
test/fixtures/battle_records.yml
test/models/battle_record_test.rb

Battle record model

---

app/controllers/user_article_controller.rb
app/javascript/packs/application.js
app/javascript/scripts/index.js
app/javascript/scripts/playground.js
app/javascript/scripts/playground_alert.js
app/javascript/styles/playground.css
app/views/typing/show.html.erb
config/routes.rb
config/webpack/environment.js
db/schema.rb

1.加入sweetalert
2.結束打字後可從彈跳視窗選擇要前往關卡選擇頁，或是要看歷史紀錄

新增美化Alert套件

---

app/controllers/typing_controller.rb
app/javascript/styles/application.css
app/javascript/styles/index.js
app/javascript/styles/playground.css
app/javascript/styles/typing.css
app/views/coding/index.html.erb
app/views/coding/show.html.erb
app/views/playground/index.html.erb
app/views/racing/index.html.erb
app/views/rooms/show.html.erb
app/views/shared/_keyboard.html.erb
app/views/shared/_timer.html.erb
app/views/shared/_topics.html.erb
app/views/stats/index.html.erb
app/views/typing/index.html.erb
app/views/typing/show.html.erb
db/schema.rb

1. partial render:
鍵盤
coding題目框
對戰區題目框
2. 全站套用統一的美術風格

Layout design

---

app/models/article.rb
app/models/ruby.rb
app/models/topic.rb
app/models/user.rb
app/models/user_topic.rb
config/routes.rb
db/migrate/20200521023435_create_topics.rb
db/migrate/20200521055820_create_user_topics.rb
db/schema.rb
db/seeds.rb
db/seeds/ruby_topic.csv
test/fixtures/topics.yml
test/fixtures/user_topics.yml
test/models/topic_test.rb
test/models/user_topic_test.rb

新增UserTopic model 
新增ruby 題目（ruby topic csv） 
seed 增加ruby題目

User topic model

---

db/migrate/20200522024848_add_user_id_and_topic_id_in_rooms_table.rb
db/schema.rb

新增user_id 及 topic_id 到rooms table

add  user_id and topic_id in rooms table

---

app/channels/room_channel.rb
app/controllers/coding_controller.rb
app/controllers/racing_controller.rb
app/controllers/rooms_controller.rb
app/controllers/typing_controller.rb
app/javascript/packs/application.js
app/javascript/packs/channels.js
app/javascript/scripts/playground.js
app/javascript/styles/playground.scss
app/views/coding/index.html.erb
app/views/coding/show.html.erb
app/views/racing/index.html.erb
app/views/rooms/show.html.erb
app/views/shared/_topics.html.erb
app/views/typing/index.html.erb

Racing page

---

app/controllers/racing_controller.rb
app/controllers/rooms_controller.rb
app/models/room.rb
app/models/user.rb
app/views/racing/index.html.erb

racing room判斷擁有者，隱藏編輯與刪除按鈕

---

app/views/racing/index.html.erb

racing頁面owner判斷修正

---

app/controllers/stats_controller.rb
app/controllers/typing_controller.rb
app/controllers/user_topics_controller.rb
app/javascript/scripts/playground.js
app/javascript/scripts/playground_alert.js
app/views/stats/index.html.erb

修正topic_controller

---

config/webpacker.yml

extract css

---

app/channels/room_channel.rb
app/controllers/messages_controller.rb
app/javascript/channels/room_channel.js
app/javascript/scripts/playground_racing.js
app/views/racing/index.html.erb
app/views/rooms/show.html.erb

racing page
在左右兩邊印出使用者是誰
把打字的正確數廣播到room
遊戲結束，判斷誰是winner，印在sweetalert上

Get winner

---

app/models/battle_record.rb
app/models/topic.rb
db/migrate/20200527013402_change_battle_records_tabel_column_type.rb
db/schema.rb

(1)更改battle_records欄位型態 
(2)建立topics與battle_records關聯

更改battle_records欄位型態 及 建立topics與battle_records關聯

---

app/channels/room_channel.rb
app/controllers/racing_controller.rb
app/controllers/rooms_controller.rb
app/javascript/styles/typing.scss
app/views/racing/index.html.erb
db/migrate/20200528085712_add_members_to_rooms.rb
db/schema.rb

在rooms table 增加members欄位，用來計算有多少人在對戰聊天室中，若有兩人，則把join按鈕鎖起來

Room members

---

app/javascript/styles/playground_racing.scss
app/views/rooms/show.html.erb

開啟Raing page preloader
Hide input area

Racing preloader

---

app/controllers/api/rooms_controller.rb
app/controllers/rooms_controller.rb
app/javascript/channels/room_channel.js
app/javascript/scripts/playground/playground_racing.js
app/javascript/styles/playground.scss
app/javascript/styles/playground_racing.scss
app/views/coding/show.html.erb
app/views/rooms/show.html.erb
app/views/typing/show.html.erb
config/routes.rb
db/schema.rb

對戰畫面區隔/Ready畫面重新設計
input框鎖定，避免滑鼠點擊（全站）
Ready頁面 等雙方登入才出現ready button
Ready後的倒數計時（input框選定提示）
對戰-ready page新增房名，確保大家進相同房間
超過兩人連到同一房間，就轉址回對戰大廳

Racing flow

---

app/javascript/scripts/playground/playground_setting.js
app/javascript/styles/_playground.scss
app/javascript/styles/playground.scss
app/views/shared/_navbar.html.erb
app/views/shared/_timer.html.erb
public/icon/droplet-dark.svg

優化打字介面的客製化色彩
新增darkmode
優化客製化按鈕

Layout customize

---

README.md

替換Readme 檔案過大的gif

---

Gemfile.lock
db/seeds/article_topic.csv
db/seeds/ruby_topic.csv

Topics csv

---

app/javascript/styles/playground_racing.scss

對戰卡片暱稱跑版修正/加陰影

---

app/javascript/styles/playground_racing.scss
app/views/rooms/show.html.erb
app/views/welcome/index.html.erb

修正landing page頁面avatar路徑問題
racing頁面 修改waiting page html位置

fix racingpagebug and welcome index avatar
